name: Build Windows Executable

on: [push] # Her push'ta çalıştırılır

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Exe Derle
        run: |
          pyinstaller --onefile --windowed pull.py

      - name: Dist Dizinini Kontrol Et
        run: |
          ls -R dist

      - name: Çıktıyı Kaydet
        uses: actions/upload-artifact@v4
        with:
          name: windows-executable
          path: dist/pull.exe # Burayı güncelle
