name: Build Windows Executable

on: [push] # Her push'ta çalıştırılır

jobs:
  build:
    runs-on: windows-latest

    steps:
      - name: Depoyu Kopyala
        uses: actions/checkout@v3

      - name: Python'u Kur
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      - name: Bağımlılıkları Yükle
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt  # Eğer dependencies yoksa bu satırı kaldır

      - name: Exe Derle
        run: pyinstaller --onefile script.py # Ana Python dosyanın adını buraya yaz

      - name: Çıktıyı Kaydet
        uses: actions/upload-artifact@v3
        with:
          name: windows-executable
          path: dist/script.exe
